[package]
name = "pw-bus"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pw-wire = { path = "../pw-wire" }
tokio = { workspace = true }
tokio-util = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = "0.3"

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
